/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `Stats` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/library"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Stats
 *
 */
export type StatsModel = runtime.Types.Result.DefaultSelection<Prisma.$StatsPayload>

export type StatsCompositeFilter = {
  equals?: Prisma.StatsObjectEqualityInput
  is?: Prisma.StatsWhereInput
  isNot?: Prisma.StatsWhereInput
}

export type StatsOrderByInput = {
  games?: Prisma.SortOrder
  wins?: Prisma.SortOrder
  losses?: Prisma.SortOrder
  elo?: Prisma.SortOrder
}

export type StatsCreateEnvelopeInput = {
  set?: Prisma.StatsCreateInput
}

export type StatsUpdateEnvelopeInput = {
  set?: Prisma.StatsCreateInput
  update?: Prisma.StatsUpdateInput
}

export type StatsWhereInput = {
  AND?: Prisma.StatsWhereInput | Prisma.StatsWhereInput[]
  OR?: Prisma.StatsWhereInput[]
  NOT?: Prisma.StatsWhereInput | Prisma.StatsWhereInput[]
  games?: Prisma.IntFilter<"Stats"> | number
  wins?: Prisma.IntFilter<"Stats"> | number
  losses?: Prisma.IntFilter<"Stats"> | number
  elo?: Prisma.IntFilter<"Stats"> | number
}

export type StatsUpdateInput = {
  games?: Prisma.IntFieldUpdateOperationsInput | number
  wins?: Prisma.IntFieldUpdateOperationsInput | number
  losses?: Prisma.IntFieldUpdateOperationsInput | number
  elo?: Prisma.IntFieldUpdateOperationsInput | number
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type StatsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetSelect<
    {
      games?: boolean
      wins?: boolean
      losses?: boolean
      elo?: boolean
    },
    ExtArgs["result"]["stats"]
  >

export type StatsSelectScalar = {
  games?: boolean
  wins?: boolean
  losses?: boolean
  elo?: boolean
}

export type StatsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  runtime.Types.Extensions.GetOmit<"games" | "wins" | "losses" | "elo", ExtArgs["result"]["stats"]>

export type $StatsPayload = {
  name: "Stats"
  objects: {}
  scalars: {
    games: number
    wins: number
    losses: number
    elo: number
  }
  composites: {}
}

export type StatsGetPayload<S extends boolean | null | undefined | StatsDefaultArgs> = runtime.Types.Result.GetResult<
  Prisma.$StatsPayload,
  S
>

/**
 * Fields of the Stats model
 */
export interface StatsFieldRefs {
  readonly games: Prisma.FieldRef<"Stats", "Int">
  readonly wins: Prisma.FieldRef<"Stats", "Int">
  readonly losses: Prisma.FieldRef<"Stats", "Int">
  readonly elo: Prisma.FieldRef<"Stats", "Int">
}

// Custom InputTypes
/**
 * Stats without action
 */
export type StatsDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the Stats
   */
  select?: Prisma.StatsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Stats
   */
  omit?: Prisma.StatsOmit<ExtArgs> | null
}
